//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartA {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PartA.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text shold contains less than 2 empty lines in a row.
        /// </summary>
        internal static string EmptyLinesAnalyzerDescription {
            get {
                return ResourceManager.GetString("EmptyLinesAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text contains 2 or more empty lines.
        /// </summary>
        internal static string EmptyLinesAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("EmptyLinesAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 or more empty lines.
        /// </summary>
        internal static string EmptyLinesAnalyzerTitle {
            get {
                return ResourceManager.GetString("EmptyLinesAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code block should be without free empty lines.
        /// </summary>
        internal static string EmptyLinesAroundCodeBlocksAnalyzerDescription {
            get {
                return ResourceManager.GetString("EmptyLinesAroundCodeBlocksAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code block contains empty line(s) in start or in end.
        /// </summary>
        internal static string EmptyLinesAroundCodeBlocksAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("EmptyLinesAroundCodeBlocksAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block contains empty lines.
        /// </summary>
        internal static string EmptyLinesAroundCodeBlocksAnalyzerTitle {
            get {
                return ResourceManager.GetString("EmptyLinesAroundCodeBlocksAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty line should be without whitespaces.
        /// </summary>
        internal static string LineConsistsInWhitespacesDescription {
            get {
                return ResourceManager.GetString("LineConsistsInWhitespacesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty line contains whitespaces.
        /// </summary>
        internal static string LineConsistsInWhitespacesMessageFormat {
            get {
                return ResourceManager.GetString("LineConsistsInWhitespacesMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line contains whitespaces.
        /// </summary>
        internal static string LineConsistsInWhitespacesTitle {
            get {
                return ResourceManager.GetString("LineConsistsInWhitespacesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The line contains whitespaces in the end.
        /// </summary>
        internal static string WhitespacesInEndOfLineMessageFormat {
            get {
                return ResourceManager.GetString("WhitespacesInEndOfLineMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The line should be without whitespaces in the end.
        /// </summary>
        internal static string WhitespacesInEndOfLinesDescription {
            get {
                return ResourceManager.GetString("WhitespacesInEndOfLinesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whitespaces in the end of line.
        /// </summary>
        internal static string WhitespacesInEndOfLineTitle {
            get {
                return ResourceManager.GetString("WhitespacesInEndOfLineTitle", resourceCulture);
            }
        }
    }
}
